//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterOrganiser
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbModuleDetail
    {
        public int ModuleDetailID { get; set; }
        public int NumberOfCredits { get; set; }
        public int NumberOfWeeks { get; set; }
        public int ClassHoursPerWeek { get; set; }
        public int ModuleHours { get; set; }
        public DayOfWeek? ScheduledDay { get; set; }
        

        public double SelfStudyHoursPerWeek
        {
            get
            {
                // Perform the calculation based on the formula
                return NumberOfCredits * 10 / NumberOfWeeks - ClassHoursPerWeek;
            }
        }
    }
}
