//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterOrganiser
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SemesterEntities : DbContext
    {
        public SemesterEntities()
            : base("name=SemesterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbModule> dbModules { get; set; }
        public virtual DbSet<dbModuleDetail> dbModuleDetails { get; set; }
        public virtual DbSet<dbRegistration> dbRegistrations { get; set; }
    }
}
